[package]
name = "Jr-desafio1-rust"
version = "0.1.0"
authors = ["Rivera-Deb <jonarsa_13@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.7"